## Je suis ....

Je suis quelqu'un de perfectionniste qui sait exécuter avec précision toutes les tâches demandées quel que soit leurs difficultés. Je m'assure toujours que chaque tâche soit parfaite mais également terminée à temps.
Je suis dynamique, créative et ouverte pour apprendre le maximum. Je suis passionnée par le domaine des statistiques et je me considère chanceuse d'avoir choisir cette filière et fière d'être une future data engineer. Je crois en destin mais le fait que je suis ESSAITIENNE n'a aucune relation avec le hasard c'est tout simplement un choix, une ambition, un amour ...

## Ma formation 

- Du 09/2016 au 06/2019 : Statistique et analyse de l’information à l'école Supérieure de la Statistique et de l’analyse de l’information ,
- Du 09/2014 au 06/2016 : Cycle préparatoire aux études d’ingénieurs Math-Physique à l'institut Préparatoire aux études d’ingénieurs d’ElManar ,
- Juin 2014 : Baccalauriat scientiﬁque Mathématique ( mention bien ) de Lycée El ARICH Tinja . 

